### ISSUE TITLE
is this a false positive or a positive ?

### ISSUE THREAD

**Issue by FlushTheCarrot** [Hazuki-san/ST-collections#1]
![image](https://github.com/user-attachments/assets/f7ef8bbb-113c-46c7-986e-52d96ef0bac3)

**Comment by Hazuki-san** [comment]
False positive, it shows as generic. Try compare the hex between original and the exe in here using VBinDiff. Otherwise apply it yourself.
https://gist.github.com/JerryLokjianming/71dac05f27f8c96ad1c8941b88030451?permalink_comment_id=5153275#gistcomment-5153275
